Repository FwMotion/3scale-cms, pull requests merged in 2023-10, with the labels that each got.

#42 Add dependabot config
  .github/dependabot.yml
Labels: enhancement, hacktoberfest-accepted

#63 Update and fix build
  .github/workflows/perform-release.yml
  .mvn/wrapper/maven-wrapper.properties
  .run/mvn clean verify -Ppitest-include-it.run.xml
  .run/mvn clean verify.run.xml
  .run/mvn generate-sources [rest-client].run.xml
  README.adoc
  cli/pom.xml
  cli/src/main/java/com/fwmotion/threescale/cms/cli/CommandBase.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/DeleteCommand.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/DiffCommand.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/DownloadCommand.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/InfoCommand.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/UploadCommand.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/config/ReflectionConfiguration.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/CmsObjectPathKeyGenerator.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/CmsSectionToTopComparator.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/LocalFileCmsObjectGenerator.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/LocalFileVisitor.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/LocalRemoteObjectTreeComparator.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/support/PathRecursionSupport.java
  cli/src/main/java/com/fwmotion/threescale/cms/cli/version/VersionProperties.java
  cli/src/main/resources/application.yaml
  mvnw
  mvnw.cmd
  parent/pom.xml
  rest-client/pom.xml
  rest-client/src/main/java/com/fwmotion/threescale/cms/ThreescaleCmsClient.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/ThreescaleCmsClientFactory.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/ThreescaleCmsClientImpl.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mappers/CmsFileMapper.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/EnumHandlerSerializer.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/FileListMixIn.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/SectionListMixIn.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/TemplateListMixIn.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/TemplateMergingList.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/AbstractPagedRestApiSpliterator.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/ApiClientBuilder.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/PagedFilesSpliterator.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/PagedSectionsSpliterator.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/PagedTemplatesSpliterator.java
  rest-client/src/main/java/com/redhat/threescale/rest/cms/XmlEnabledApiClient.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/ThreescaleCmsClientImplUnitTest.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/mappers/CmsFileMapperUnitTest.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/mappers/CmsTemplateMapperUnitTest.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/CmsFileMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/CmsLayoutMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/CmsObjectMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/CmsSectionMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/HeaderMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/InputStreamContentsMatcher.java
Labels: enhancement, dependencies

#67 Enhance GitHub Actions workflow for performing releases
  .github/dependabot.yml
  .github/workflows/build-container-image.yml
  .github/workflows/perform-release.yml
  .github/workflows/pull-request-tests.yml
  parent/pom.xml
Labels: enhancement, build

#70 Set up maven remote repository filtering
  .github/workflows/build-container-image.yml
  .github/workflows/perform-release.yml
  .github/workflows/pull-request-tests.yml
  .github/workflows/submit-dependency-tree-samples.yml
  .mvn/filters/groupId-imposter.txt
  .mvn/maven.config
Labels: build

#24 Add Javadoc and site generation
  .github/workflows/perform-release.yml
  .github/workflows/render-and-deploy-site.yml
  cli/pom.xml
  cli/src/site/site.xml
  parent/pom.xml
  parent/src/site/site.xml
  pom.xml
  rest-client/pom.xml
  rest-client/src/main/dokka/module.md
  rest-client/src/main/dokka/packages.md
  rest-client/src/main/java/com/redhat/threescale/rest/cms/XmlEnabledApiClient.java
  rest-client/src/site/site.xml
  src/site/site.xml
Labels: documentation

#83 Add support for builtin_section
  rest-client/src/main/java/com/fwmotion/threescale/cms/ThreescaleCmsClientImpl.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mappers/CmsBuiltinSectionMapper.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/SectionListMixIn.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/mixins/SectionMergingList.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/model/CmsBuiltinSection.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/model/CmsSection.java
  rest-client/src/main/java/com/fwmotion/threescale/cms/support/PagedSectionsSpliterator.java
  rest-client/src/main/resources/api-spec/3scale-cms.yaml
  rest-client/src/test/java/com/fwmotion/threescale/cms/ThreescaleCmsClientImplIntegrationTest.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/ThreescaleCmsClientImplUnitTest.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/matchers/CmsBuiltinSectionMatcher.java
  rest-client/src/test/java/com/fwmotion/threescale/cms/testsupport/SectionsApiTestSupport.java
  rest-client/src/test/resources/imposter/responses/list-sections-1.xml
Labels: enhancement

#86 Make updates to release scripts
  .github/workflows/build-container-image.yml
  .github/workflows/perform-release.yml
  .github/workflows/render-and-deploy-site.yml
  cli/pom.xml
  cli/src/site/site.xml
  parent/pom.xml
  parent/src/site/site.xml
  pom.xml
  rest-client/src/site/site.xml
  src/site/site.xml
Labels: enhancement

#87 Don't create parent directory on download if not specified
  cli/src/main/java/com/fwmotion/threescale/cms/cli/DownloadCommand.java
Labels: bug
